### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Monokiro** [hachchch/-GeneCiv-#5]
Well hello there 👋
Crash upon advancing to the next era.

![Screenshot_2023-12-13-13-46-59-784_com.unciv.app.jpg](https://github.com/hachchch/-GeneCiv-/assets/5355318/f5a8a610-070d-4ccd-9411-50ef9cf223d9)

**Message:**
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1574)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1607)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1605)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:314)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:307)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:115)
	at com.unciv.logic.civilization.managers.TechManager.moveToNewEra(TechManager.kt:445)
	at com.unciv.logic.civilization.managers.TechManager.addTechnology(TechManager.kt:342)
	at com.unciv.logic.civilization.managers.TechManager.addTechnology$default(TechManager.kt:284)
	at com.unciv.logic.civilization.managers.TechManager.addScience(TechManager.kt:262)
	at com.unciv.logic.civilization.managers.TechManager.endTurn(TechManager.kt:249)
	at com.unciv.logic.civilization.managers.TurnManager.endTurn(TurnManager.kt:277)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:358)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:617)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by hachchch** [comment]
wow, thanks to find fatal bug.

**Comment by Monokiro** [comment]
Well i could fix that one, but I can't afford to join your beautiful project at the moment ❤️

**Comment by hachchch** [comment]
Lol, okay
Until the bug is fixed, it is fun to start with Carboniferous period.

**Comment by hachchch** [comment]
@Monokiro 
The mod was updated!
Now, you can move the Devonian to Carboniferous
